version: '2.1'
orbs:
  node: circleci/node@4.7.0
  sam: circleci/aws-sam-serverless@3.2
jobs:
  build_and_test: # this can be any name you choose
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths: .
workflows:
  build_and_deploy:
    jobs:
      - build_and_test
      - sam/deploy:
          context: personal-AWS-context-<< pipeline.git.branch >>
          name: deploy-staging
          requires:
            - build_and_test
          s3-bucket: prime123456
          stack-name: staging-stack
          template: template.yaml
          version:
