version: '2.1'
orbs:
  sam: circleci/aws-sam-serverless@3.2
jobs:
  test_my_api:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - run: echo "Run your API tests here"
workflows:
  test_and_deploy:
    jobs:
      - sam/deploy:
          context: personal-AWS-context
          name: deploy-staging
          s3-bucket: my-s3-bucket
          stack-name: staging-stack
          template: ./path/to/template.yml
