version: '2.1'
orbs:
  sam: circleci/aws-sam-serverless@3.2
jobs:
  lambda_build:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - run: npm install
workflows:
  test_and_deploy:
    jobs:
      - lambda_build:
      - sam/deploy:
          context: personal-AWS-context-<< pipeline.git.branch >>
          name: deploy-staging
          requires:
            - lambda-build
          s3-bucket: prime123456
          stack-name: staging-stack
          template: template.yaml
          version:
